# Generated by Django 5.2.16 on 2026-07-13 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Overdue'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('rule_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_tasks', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_tasks', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='followups.followuptask')),
            ],
        ),
        migrations.AddIndex(
            model_name='followuptask',
            index=models.Index(fields=['business', 'assigned_user', 'due_at', 'status'], name='followups_f_busines_71e242_idx'),
        ),
        migrations.AddIndex(
            model_name='followuptask',
            index=models.Index(fields=['business', 'lead', 'status'], name='followups_f_busines_7fdd57_idx'),
        ),
        migrations.AddConstraint(
            model_name='followuptask',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'overdue')), models.Q(('rule_key', ''), _negated=True)), fields=('business', 'lead', 'rule_key'), name='unique_open_automated_followup_per_rule'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['business', 'recipient', 'read_at', 'created_at'], name='followups_n_busines_8939a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('task', 'recipient'), name='unique_notification_per_task_recipient'),
        ),
    ]
