# Generated by Django 5.2.16 on 2026-07-13 09:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('referral', 'Referral'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('walk_in', 'Walk-in'), ('website', 'Website'), ('phone_call', 'Phone call'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='other', max_length=20)),
                ('stage', models.CharField(choices=[('new_inquiry', 'New inquiry'), ('contacted', 'Contacted'), ('site_visit', 'Site visit'), ('quotation_sent', 'Quotation sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new_inquiry', max_length=20)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lost_reason', models.TextField(blank=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'is_active'], name='leads_produ_busines_8bb7d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_product_name_per_business'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['business', 'stage'], name='leads_lead_busines_bfbda2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['business', 'assigned_user', 'last_activity_at'], name='leads_lead_busines_49f2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['business', 'created_at'], name='leads_lead_busines_7e9b2a_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('quoted_price__isnull', True), ('quoted_price__gte', 0), _connector='OR'), name='lead_quoted_price_is_not_negative'),
        ),
    ]
