# Generated by Django 5.2.16 on 2026-07-14 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('leads', '0002_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['business', 'stage', '-last_activity_at'], name='lead_biz_stage_activity_idx'),
        ),
    ]
