# Generated by Django 5.2.16 on 2026-07-17 07:09

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_unique_user_email_case_insensitive'),
        ('leads', '0003_lead_lead_biz_stage_activity_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_name_per_business',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('business'), name='unique_product_name_per_business'),
        ),
    ]
