"""
Django settings for cuein project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_local_env(path: Path) -> None:
    """Load simple KEY=value entries for local development only."""
    if not path.exists():
        return

    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip())


load_local_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

ENVIRONMENT = os.environ.get('DJANGO_ENV', 'development').lower()
IS_PRODUCTION = ENVIRONMENT == 'production'
DEBUG = os.environ.get('DJANGO_DEBUG', 'false' if IS_PRODUCTION else 'true').lower() == 'true'

if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured('DJANGO_DEBUG must be false in production.')

# A predictable development key keeps local setup simple, but production must
# supply its own secret through the environment.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if IS_PRODUCTION:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be configured in production.')
    SECRET_KEY = 'django-insecure-development-only-change-before-production'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]
if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS must be configured in production.')

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

SECURE_SSL_REDIRECT = IS_PRODUCTION
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_HSTS_SECONDS = 31_536_000 if IS_PRODUCTION else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get(
    'DJANGO_HSTS_INCLUDE_SUBDOMAINS',
    'false',
).lower() == 'true'
SECURE_HSTS_PRELOAD = os.environ.get('DJANGO_HSTS_PRELOAD', 'false').lower() == 'true'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'

TRUST_X_FORWARDED_FOR = os.environ.get('DJANGO_BEHIND_PROXY', '').lower() == 'true'
if TRUST_X_FORWARDED_FOR:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'core.apps.CoreConfig',
    'leads',
    'followups',
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = 'cuein.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cuein.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['POSTGRES_DB'],
        'USER': os.environ['POSTGRES_USER'],
        'PASSWORD': os.environ['POSTGRES_PASSWORD'],
        'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# User-uploaded profile pictures. In production these files should be served
# by the deployment's media storage; Django serves them locally in DEBUG mode.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Defining STORAGES replaces Django's complete storage registry. Keep an
# explicit default backend for uploaded profile pictures alongside WhiteNoise
# for static assets, otherwise accessing ``profile_picture.url`` raises an
# InvalidStorageError at render time.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'OPTIONS': {
            'location': MEDIA_ROOT,
            'base_url': MEDIA_URL,
        },
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

LOGIN_URL = 'web:login'
LOGIN_REDIRECT_URL = 'web:dashboard'
LOGOUT_REDIRECT_URL = 'web:login'

# Registrations remain pending until their owner enters the emailed code.
# In development, Django prints the message to the terminal; production uses
# the SMTP values supplied through environment variables.
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Cuein <no-reply@cuein.local>')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'false').lower() == 'true'
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '10'))
EMAIL_VERIFICATION_TIMEOUT = int(os.environ.get('EMAIL_VERIFICATION_TIMEOUT', str(24 * 60 * 60)))
EMAIL_VERIFICATION_RESEND_COOLDOWN = int(os.environ.get('EMAIL_VERIFICATION_RESEND_COOLDOWN', '60'))
# Password-reset codes are intentionally shorter-lived than signup codes.
PASSWORD_RESET_TIMEOUT = int(os.environ.get('PASSWORD_RESET_TIMEOUT', str(15 * 60)))
PASSWORD_RESET_RESEND_COOLDOWN = int(os.environ.get('PASSWORD_RESET_RESEND_COOLDOWN', '60'))

# Browser posts do not pass through DRF, so they use the same shared cache
# through core.security. Code records still have their own five-attempt cap.
BROWSER_AUTH_THROTTLE_RATES = {
    'web_signup': '5/hour',
    'web_email_verify': '10/hour',
    'web_email_resend': '3/hour',
    'web_password_reset_request': '3/hour',
    'web_password_reset_confirm': '10/hour',
    'web_login': '10/minute',
}

LOGIN_FAILURE_WINDOW = int(os.environ.get('LOGIN_FAILURE_WINDOW', str(60 * 60)))
LOGIN_BACKOFF_FAILURE_THRESHOLD = int(os.environ.get('LOGIN_BACKOFF_FAILURE_THRESHOLD', '3'))
LOGIN_BACKOFF_BASE_SECONDS = int(os.environ.get('LOGIN_BACKOFF_BASE_SECONDS', '30'))
LOGIN_BACKOFF_MAX_SECONDS = int(os.environ.get('LOGIN_BACKOFF_MAX_SECONDS', str(15 * 60)))
LOGIN_CAPTCHA_FAILURE_THRESHOLD = int(os.environ.get('LOGIN_CAPTCHA_FAILURE_THRESHOLD', '3'))

# Turnstile is intentionally opt-in: normal sign-ins never see it, and it is
# required only after repeated failures once both deployment keys are set.
TURNSTILE_SITE_KEY = os.environ.get('TURNSTILE_SITE_KEY', '')
TURNSTILE_SECRET_KEY = os.environ.get('TURNSTILE_SECRET_KEY', '')
TURNSTILE_VERIFY_URL = 'https://challenges.cloudflare.com/turnstile/v0/siteverify'
TURNSTILE_TIMEOUT = int(os.environ.get('TURNSTILE_TIMEOUT', '5'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# This must be configured before the first migration is created.
AUTH_USER_MODEL = 'core.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'core.authentication.BusinessScopedJWTAuthentication',
        'core.authentication.WorkspaceSessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Scoped throttles below apply only to public authentication routes. They
    # use the shared Redis cache configured in CACHES, so limits hold across
    # application workers.
    'DEFAULT_THROTTLE_RATES': {
        'auth_signup': '5/hour',
        'auth_email_verify': '5/hour',
        'auth_email_resend': '3/hour',
        'auth_password_reset_request': '3/hour',
        'auth_password_reset_confirm': '10/hour',
        'auth_token': '10/minute',
        'auth_token_refresh': '30/minute',
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
REDIS_CACHE_URL = os.environ.get('REDIS_CACHE_URL', 'redis://127.0.0.1:6379/1')
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_CACHE_URL,
        'TIMEOUT': 60,
        'OPTIONS': {
            'socket_connect_timeout': 1,
            'socket_timeout': 1,
        },
    },
}
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', '').lower() == 'true'
CELERY_BEAT_SCHEDULE = {
    'flag-overdue-follow-up-tasks-hourly': {
        'task': 'followups.tasks.flag_overdue_tasks',
        'schedule': 60 * 60,
    },
    'schedule-stale-lead-escalations-daily': {
        'task': 'followups.tasks.schedule_stale_lead_escalations',
        'schedule': 24 * 60 * 60,
    },
}
