# Generated by Django 5.2.16 on 2026-07-14 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('accounting', 'Accounting'), ('agriculture', 'Agriculture'), ('architecture', 'Architecture'), ('automotive', 'Automotive'), ('beauty_wellness', 'Beauty & wellness'), ('cleaning', 'Cleaning services'), ('consulting', 'Consulting'), ('education', 'Education & training'), ('electrical', 'Electrical services'), ('events', 'Events & catering'), ('facility_management', 'Facility management'), ('furniture', 'Furniture'), ('healthcare', 'Healthcare'), ('home_improvement', 'Home improvement'), ('hospitality', 'Hospitality'), ('information_technology', 'Information technology'), ('insurance', 'Insurance'), ('interior_design', 'Interior design'), ('landscaping', 'Landscaping'), ('legal', 'Legal services'), ('logistics', 'Logistics & delivery'), ('manufacturing', 'Manufacturing'), ('marketing', 'Marketing & advertising'), ('maintenance', 'Maintenance & repair'), ('plumbing', 'Plumbing'), ('real_estate', 'Real estate'), ('retail', 'Retail'), ('solar', 'Solar'), ('cctv', 'CCTV / Security'), ('ac_installation', 'AC installation'), ('construction', 'Construction'), ('security', 'Security services'), ('telecommunications', 'Telecommunications'), ('travel', 'Travel & tourism'), ('other', 'Other')], default='other', max_length=32)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=64)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'pending registration',
                'verbose_name_plural': 'pending registrations',
            },
        ),
    ]
