# Generated by Django 5.2.16 on 2026-07-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pending_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='verification_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='verification_code_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
