# Generated by Django 5.2.16 on 2026-07-15 07:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('salesperson', 'Salesperson')], default='salesperson', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('joined_at', 'id'),
                'indexes': [models.Index(fields=['user', 'is_active'], name='core_member_user_id_dec2d3_idx'), models.Index(fields=['business', 'is_active'], name='core_member_busines_8499e5_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'business'), name='unique_user_membership_per_business')],
            },
        ),
    ]
