# Generated by Django 5.2.16 on 2026-07-17 07:03

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='timezone',
            field=models.CharField(default='Asia/Karachi', max_length=64, validators=[core.validators.validate_iana_timezone]),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='timezone',
            field=models.CharField(default='Asia/Karachi', max_length=64, validators=[core.validators.validate_iana_timezone]),
        ),
    ]
