# Generated by Django 5.2.16 on 2026-07-17 07:09

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0008_alter_business_timezone_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='unique_user_username_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='unique_user_email_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='pendingregistration',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='unique_pending_registration_username_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='pendingregistration',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_pending_registration_email_case_insensitive'),
        ),
    ]
